## server
server:
  port: 8080
  servlet:
    context-path: /

## spring
spring:
  ## 应用
  application:
    name: buukle-gates
  ## 数据源
  datasource:
    url: jdbc:mysql://39.107.78.160:3654/buukle-gates?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: A987654321b/
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  ## 网关
  cloud:
    gateway:
      ## 设置注册中心可见
      discovery:
        locator:
          enabled: true
      routes:
        ## 网关路由到 static 服务
        - id: static
          uri: lb://BUUKLE-WWW
          predicates:
            - Host=tstatic.buukle.top:8080
         ## 网关路由到 www 服务
        - id: www
          uri: lb://BUUKLE-WWW
          predicates:
            - Host=twww.buukle.top:8080
         ## 网关路由到 timeline 服务 (暂时与www在同一项目开发)
        - id: timeline
          uri: lb://BUUKLE-WWW
          ## uri: lb://BUUKLE-TIMELINE
          predicates:
            - Host=timeline.buukle.top:8080
         ## 网关路由到 cms 服务
        - id: cms
          uri: lb://BUUKLE-CMS
          predicates:
            - Host=tcms.buukle.top:8080
         ## 网关路由到 security 服务
        - id: security
          uri: lb://BUUKLE-SECURITY
          predicates:
            - Host=tsecurity.buukle.top:8080
         ## 网关路由到 passport 服务
        - id: passport
          uri: lb://BUUKLE-SECURITY
          predicates:
            - Host=tpassport.buukle.top:8080
         ## 网关路由到 wjs(worker job system) 服务
        - id: wjs
          uri: lb://BUUKLE-WJS
          predicates:
            - Host=twjs.buukle.top:8080
         ## 网关路由到 activiti 服务
        - id: activiti
          uri: lb://BUUKLE-ACTIVITI
          predicates:
            - Host=tactiviti.buukle.top:8080
  #redis
  redis:
    database: 5
    host: 39.105.74.47
    port: 4376
    jedis:
      pool:
        max-active: 100
        max-idle: 100
        max-wait: -1
        min-idle: 10
    timeout: 3000
## 注册中心
eureka:
  instance:
    hostname: 192.168.254.27
    prefer-ip-address: true
    serverport: 9090
  client:
    serviceUrl:
       defaultZone: http://${eureka.instance.hostname}:${eureka.instance.serverport}/eureka/

##mybatis
mybatis:
  mapper-locations: classpath*:/config/mapper/*.xml
  type-aliases-package: top.buukle.cloud.gates.entity
## 日志
logging:
  config: classpath:config/spring/springBoot-logbak-local.xml